import requests
import json
import time
from datetime import datetime
from lomond import WebSocket
from unidecode import unidecode
import colorama
import re
from dhooks import Webhook, Embed
import websocket
import random
import base64
from websocket import create_connection	
from bs4 import BeautifulSoup

webhook_url = "https://discordapp.com/api/webhooks/731852323185360897/mXlbfkA959ErWPE3PaRC8jTdxE0iy4b5y03B92K7XeIPI5W9hs9k_O6iRRzk0ZtcbMgZ"

hook = Webhook(webhook_url)
try:
	hook = Webhook(webhook_url)
except:
	print("Invalid WebHook Url!")

url = "https://lms.vedantu.com/lms/homefeed/getTodaysLiveQuizSchedule?requestSource=ANDROID&appDeviceId=c8e1c7b57f90e0d&appVersionCode=1.6.8&callingUserId=4102441978683815"
headers = {
	'Host':'lms.vedantu.com',
	'accept':'application/json.text/plain,*/*',
	'x-ved-device':'ANDROID',
	'x-ved-token':'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3OTkxMTM5NjY1IiwiZXhwIjoxNjAwMDA5MDI0LCJpc3MiOiJ2ZWRhbnR1LmNvbSIsInNlc3Npb25EYXRhIjoie1wiZmlyc3ROYW1lXCI6XCJNb2hpdFwiLFwibGFzdE5hbWVcIjpcIlJhaiBcIixcInVzZXJJZFwiOjQxMDI0NDE5Nzg2ODM4MTUsXCJyb2xlXCI6XCJTVFVERU5UXCIsXCJjb250YWN0TnVtYmVyXCI6XCI3OTkxMTM5NjY1XCIsXCJwaG9uZUNvZGVcIjpcIjkxXCIsXCJjcmVhdGlvblRpbWVcIjoxNTk0ODE5NDM3NTc4LFwiZXhwaXJ5VGltZVwiOjE2MDAwMDkwMjQ1MTksXCJpc0VtYWlsVmVyaWZpZWRcIjpmYWxzZSxcImlzQ29udGFjdE51bWJlclZlcmlmaWVkXCI6dHJ1ZSxcImlzQ29udGFjdE51bWJlckRORFwiOmZhbHNlLFwiaXNDb250YWN0TnVtYmVyV2hpdGVsaXN0ZWRcIjpmYWxzZSxcInJlZmVycmFsQ29kZVwiOlwibW9oaTllZWNcIixcImRldmljZVwiOlwiQU5EUk9JRFwiLFwiZ3JhZGVcIjpcIjEwXCIsXCJib2FyZFwiOlwiQ0JTRVwiLFwiZXhhbVRhcmdldHNcIjpbXSxcInVzZXJJblByb2Nlc3NPZk9uYm9hcmRpbmdcIjpmYWxzZX0ifQ.GSDcGbapO4ktTItzLSA3a5TZNK_AKBM8rlCHW3fGGZckSoy0qKNz0NZEcXftlWB4iOQwmQNOduOUwj7n2Yxbyg',
	'accept-encoding':'gzip',
	'cookie':'X-Ved-Token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3OTkxMTM5NjY1IiwiZXhwIjoxNjAwMDA5MDI0LCJpc3MiOiJ2ZWRhbnR1LmNvbSIsInNlc3Npb25EYXRhIjoie1wiZmlyc3ROYW1lXCI6XCJNb2hpdFwiLFwibGFzdE5hbWVcIjpcIlJhaiBcIixcInVzZXJJZFwiOjQxMDI0NDE5Nzg2ODM4MTUsXCJyb2xlXCI6XCJTVFVERU5UXCIsXCJjb250YWN0TnVtYmVyXCI6XCI3OTkxMTM5NjY1XCIsXCJwaG9uZUNvZGVcIjpcIjkxXCIsXCJjcmVhdGlvblRpbWVcIjoxNTk0ODE5NDM3NTc4LFwiZXhwaXJ5VGltZVwiOjE2MDAwMDkwMjQ1MTksXCJpc0VtYWlsVmVyaWZpZWRcIjpmYWxzZSxcImlzQ29udGFjdE51bWJlclZlcmlmaWVkXCI6dHJ1ZSxcImlzQ29udGFjdE51bWJlckRORFwiOmZhbHNlLFwiaXNDb250YWN0TnVtYmVyV2hpdGVsaXN0ZWRcIjpmYWxzZSxcInJlZmVycmFsQ29kZVwiOlwibW9oaTllZWNcIixcImRldmljZVwiOlwiQU5EUk9JRFwiLFwiZ3JhZGVcIjpcIjEwXCIsXCJib2FyZFwiOlwiQ0JTRVwiLFwiZXhhbVRhcmdldHNcIjpbXSxcInVzZXJJblByb2Nlc3NPZk9uYm9hcmRpbmdcIjpmYWxzZX0ifQ.GSDcGbapO4ktTItzLSA3a5TZNK_AKBM8rlCHW3fGGZckSoy0qKNz0NZEcXftlWB4iOQwmQNOduOUwj7n2Yxbyg',
	'user-agent':'okhttp/3.14.4'
}
r =requests.get(url,headers=headers)
rdata = r.text
print(rdata)
